# Generated by Django 5.2.17 on 2026-10-06 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoSpatialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='geospatial/')),
                ('file_name', models.CharField(max_length=255)),
                ('crs', models.CharField(max_length=100)),
                ('feature_count', models.IntegerField()),
                ('status', models.CharField(default='PROCESSING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.IntegerField()),
                ('geometry_type', models.CharField(max_length=50)),
                ('geometry', models.JSONField()),
                ('properties', models.JSONField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app_geo.geospatialfile')),
            ],
        ),
    ]
