# Generated by Django 5.2.17 on 2026-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialfile',
            name='feature_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geospatialfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
